---   
   ## This play configure cluster quotas for services and create buckets.
   - name: couchbase status   ## Control for database status, exit if it is not running.
     shell: |
      . ~couchbase/.bash_profile
      /couchbase/cb_home/opt/couchbase/bin/couchbase-server --status
     register: couchbase_status   

   - name: couchbase status
     fail:
      msg: "{{couchbase_status.stdout}}"
     when: couchbase_status.stdout != 'Couchbase Server is running'  

   - name: change index_quota 
     shell: |
        . ~couchbase/.bash_profile
        couchbase-cli setting-cluster -c {{init_node}}:8091 --username {{admin_user}}  --password {{admin_password}} --cluster-index-ramsize {{index_quota}}
     when: index_quota is defined  

   - name: change data quota
     shell: |
        . ~couchbase/.bash_profile
        couchbase-cli setting-cluster -c {{init_node}}:8091 --username {{admin_user}}  --password {{admin_password}} --cluster-ramsize {{data_quota}}
     when: data_quota is defined   

   - name: change analytics quota
     shell: |
        . ~couchbase/.bash_profile
        couchbase-cli setting-cluster -c {{init_node}}:8091 --username {{admin_user}}  --password {{admin_password}} --cluster-analytics-ramsize {{analytics_quota}}
     when: analytics_quota is defined   

   - name: change eventing quota
     shell: |
        . ~couchbase/.bash_profile
        couchbase-cli setting-cluster -c {{init_node}}:8091 --username {{admin_user}}  --password {{admin_password}} --cluster-eventing-ramsize {{eventing_quota}}    
     when: eventing_quota is defined   

   - name: create bucket
     shell: |
        . ~couchbase/.bash_profile
        couchbase-cli bucket-create --cluster {{init_node}}:8091 --username {{admin_user}} --password {{admin_password}} --bucket {{item.bucket_name}} --bucket-type {{item.bucket_type}} --durability-min-level {{item.durability_level}} --bucket-ramsize {{item.bucket_ram_size}} --bucket-replica {{item.bucket_replica}} --compression-mode {{item.compression_mode}} --enable-index-replica {{item.index_replica}}    
     with_items:
       - "{{ bucket_list }}"
     when: item.bucket_name is defined   
        
   - name: couchbase status
     shell: |
       . ~couchbase/.bash_profile
       /couchbase/cb_home/opt/couchbase/bin/couchbase-cli server-list -c {{init_node}}:8091 --username {{admin_user}} --password {{admin_password}}
     register: couchbase_cluster_health   
     
   - name: couchbase status
     debug:
      msg: "{{couchbase_cluster_health.stdout_lines}}"

                  
